# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ./convert
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Convert files
      working-directory: ./convert
      run: |
        # run the script to convert conf files
        python convert.py
        
    - name: commit and push
      run: |
        git config --global user.name 'auto generated'
        git config --global user.email 'auto_genereated@example.com'
        git add .
        git commit -m "automatic update"
        git push
